# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - about.md

footer: 'follow us on <a href="https://twitter.com/m0tl3ycr3w">twitter</a>'

#style: light # dark (default) or light

plugins:
  - jekyll-seo-tag
